//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimitryExercise2.Model
{
    using System;
    
    [Flags]
    public enum Courses : int
    {
        Sql = 1,
        Azure = 2,
        Html = 4,
        Css = 8,
        JavaScript = 16,
        CSharp = 32,
        OOP = 64,
        AspNet = 128
    }
}
