//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimitryExercise2.Model
{
    using System;
    
    public enum Course : int
    {
        CSharp = 0,
        OOP = 1,
        Azure = 2,
        Solid = 3,
        Html = 4,
        Css = 5,
        JavaScript = 6,
        Sql = 7
    }
}
